version: '3.5'
services:
  nexus:
    image: sonatype/nexus3:3.30.0
    container_name: nexus
    hostname: nexus
    restart: always
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx4g -XX:MaxDirectMemorySize=4g"
      NEXUS_CONTEXT: "nexus"
    ports:
      - 8787:8081
    # expose:
    #   - 8081
    volumes:
      - /DATA/DevOps/nexus:/nexus-data
    networks:
      - nexus-network

networks:
  nexus-network:
    external: true
    name: devops-network